export const SCREEN_UI_DATA = {
  FdCalculator: {
    screenTitle: 'FdCalculator',
    name: 'FD Calculator',
    input1Label: 'Deposit amount',
    input1Placeholder: 'Enter Deposit amount',
    input2Label: 'Rate of interest',
    input2Placeholder: 'Enter interest rate',
    input3Label: 'Tenure',
    input3Placeholder: 'Enter Period',
    input4Label: 'Frequency',
    input4Placeholder: 'Frequency',
    input5Label: 'Investment Date -',
    input5Placeholder: '',
  },
  RdCalculator: {
    screenTitle: 'RdCalculator',
    name: 'RD Calculator',
    input1Label: 'Monthly Deposit',
    input1Placeholder: 'Enter Monthly Deposit',
    input2Label: 'Rate of interest',
    input2Placeholder: 'Enter interest rate',
    input3Label: 'Saving term',
    input3Placeholder: 'Enter term',
    input4Label: '',
    input4Placeholder: '',
    input5Label: 'Investment Date -',
    input5Placeholder: '',
  },
  PpfCalculator: {
    screenTitle: 'PpfCalculator',
    name: 'PPF Calculator',
    input1Label: 'Deposit amount',
    input1Placeholder: 'Enter Deposit amount',
    input2Label: 'Rate of interest',
    input2Placeholder: 'Enter interest rate',
    input3Label: 'Enter Years',
    input3Placeholder: 'Enter Years',
    input4Label: 'Investment Frequency',
    input4Placeholder: 'Frequency',
    input5Label: 'Investment Date -',
    input5Placeholder: '',
  },
};

export const SCREEN_NAMES = {
  EmiCalculator: 'EmiCalculator',
  DetailScreen: 'DetailScreen',
  InDepthDetailScreen: 'InDepthDetailScreen',
  CompareLoansScreen: 'CompareLoansScreen',
  LoanComparisonDetails: 'LoanComparisonDetails',
  FdCalculator: 'FdCalculator',
  RdCalculator: 'RdCalculator',
  PpfdCalculator: 'PpfCalculator',
  AmountToWordsScreen: 'AmountToWordsScreen',
  MoneyTotallerScreen: 'MoneyTotallerScreen',
};
