export const SCREEN_EMI_UI_DATA = {
  EmiCalculator: {
    screenTitle: 'EmiCalculator',
    name: 'EMI Calculator',
    input1Label: 'Loan amount',
    input1Placeholder: 'Enter Loan amount',
    input2Label: 'Interest',
    input2Placeholder: 'Enter interest rate',
    input3Label: 'Period',
    input3Placeholder: 'Enter Period',
    input4Label: 'Frequency',
    input4Placeholder: 'Frequency',
    input5Label: 'Investment Date -',
    input5Placeholder: '',
  },
  HomeLoanCalculator: {
    screenTitle: 'HomeLoanCalculator',
    name: 'Home Loan Calculator',
    input1Label: 'Home Loan amount',
    input1Placeholder: 'Enter Home Loan amount',
    input2Label: 'Rate of interest',
    input2Placeholder: 'Enter interest rate',
    input3Label: 'Period',
    input3Placeholder: 'Enter Period',
    input4Label: '',
    input4Placeholder: '',
    input5Label: 'Investment Date -',
    input5Placeholder: '',
  },
  PpfCalculator: {
    screenTitle: 'PpfCalculator',
    name: 'PPF Calculator',
    input1Label: 'Deposit amount',
    input1Placeholder: 'Enter Deposit amount',
    input2Label: 'Rate of interest',
    input2Placeholder: 'Enter interest rate',
    input3Label: 'Enter Years',
    input3Placeholder: 'Enter Years',
    input4Label: 'Investment Frequency',
    input4Placeholder: 'Frequency',
    input5Label: 'Investment Date -',
    input5Placeholder: '',
  },
};

export const SCREEN_NAMES = {
  EmiCalculator: 'EmiCalculator',
  DetailScreen: 'DetailScreen',
  InDepthDetailScreen: 'InDepthDetailScreen',
  CompareLoansScreen: 'CompareLoansScreen',
  LoanComparisonDetails: 'LoanComparisonDetails',
  FdCalculator: 'FdCalculator',
  RdCalculator: 'RdCalculator',
  PpfdCalculator: 'PpfCalculator',
  AmountToWordsScreen: 'AmountToWordsScreen',
  MoneyTotallerScreen: 'MoneyTotallerScreen',
};
